### ISSUE TITLE
Eureka/Bozja data when a character has no Bozja

### ISSUE THREAD

**Issue by richardjarrell** [xivapi/godestone#17]
**Describe the bug**
When a character has never done Bozja content but has done Eureka, Bozja data is parsed as if it is Eureka data.

**To Reproduce**
parse character id 3981995 (Amet Sy @ Famfrit)

**Expected behavior**
A ClassJobBozjan object with 0s and a ClassJobElemental object with Eureka data.

**Additional context**
Objects returned appear as such
`ClassJobBozjan: { 
Level: 2, 
Mettle: 642, 
Name: "Elemental Level" 
}`
`ClassJobElemental: { 
ExpLevel: 0, 
ExpLevelMax: 0, 
ExpLevelTogo: 0, 
Level: 0, 
Name: "" 
},`

**Comment by karashiiro** [comment]
This is probably more of a selectors bug, but it doesn't have a solution: https://github.com/xivapi/lodestone-css-selectors/issues/12

**Comment by karashiiro** [comment]
I should be able to add special handling for this.

**Comment by karashiiro** [comment]
Released v2.1.5, let me know if that fixes it.

**Comment by richardjarrell** [comment]
I originally mentioned it as a selectors bug in xivapi Discord but I had no idea how it could be fixed.
This seems to have handled it perfectly.  I really appreciate it.  Hopefully whatever the new Eureka/Bozja is will get better selectors on the Lodestone.
